### ISSUE TITLE
Only Ventura image has ARM binaries

### ISSUE THREAD

**Issue by slonopotamus** [macOScontainers/macos-jail#12]
The issue is that GitHub Actions uses x86 macOS that doesn't have arm libraries. Ventura image has them because I built that image on my M1 MacBook.

https://github.com/macOScontainers/macos-jail/issues/6#issuecomment-1732538252

**Comment by ArthurPKFX** [comment]
Willing to build the Monterey image on the M1 I have access to if there are instructions for that

**Comment by slonopotamus** [comment]
See [readme](https://github.com/macOScontainers/macos-jail#macos-jail).

**Comment by ArthurPKFX** [comment]
Had to modify `macosjail/mkjail.files` with `/System/Library/dyld/dyld_shared_cache_* /System/Library/dyld/` as a glob but got a working image at `ghcr.io/arthurpkfx/macos-jail/monterey`

**Comment by jhay06** [comment]
cans someone build ventura for amd64 ? or sonoma for amd64 thank you

**Comment by slonopotamus** [comment]
I _think_ current Ventura image is multi-arch and can be run on both arm and amd. Do you have any issues with it?

**Comment by jhay06** [comment]
i tried to pull this image , but after downloading and execute the sample 
docker run --rm -it ghcr.io/macoscontainers/macos-jail/ventura:latest echo "Hello from macOS container ^_^"

it says "exec error" , this error appears when the executable is not supported or run from incompatible arch . 
also at the top of that exec error there is a line 
WARNING: The requested image's platform (unknown) does not match the detected host platform (darwin/amd64/v2) and no specific platform was requested

**Comment by jhay06** [comment]
hoping for latest update for ventura to work with intel/amd64 , thank you
