### ISSUE TITLE
Build images using GitHub Actions

### ISSUE THREAD

**Issue by slonopotamus** [macOScontainers/macos-jail#6]
Subj

**Comment by slonopotamus** [comment]
https://github.com/macOScontainers/macos-jail/actions/runs/5602808113

**Comment by slonopotamus** [comment]
Problem: GitHub Actions uses x86 macOS that doesn't have arm libraries. Waiting for https://github.com/actions/runner-images/issues/2187

**Comment by Ludea** [comment]
https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/ maybe relevant ?

**Comment by slonopotamus** [comment]
We can use https://www.flyci.net/

**Comment by slonopotamus** [comment]
Woah! https://github.com/actions/runner-images/issues/9254

**Comment by slonopotamus** [comment]
Aaaand FlyCI already removes macOS runners: https://flyci.net/blog/flyci-discontinue-macos-runners
